name: Release on Main Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Combine .pem files into JSON
        run: |
          mkdir -p output
          echo "[" > output/combined.json
          first=true
          for file in $(find . -name "*.pem"); do
            content=$(cat $file | sed ':a;N;$!ba;s/\n/\\n/g')
            if [ "$first" = true ]; then
              first=false
            else
              echo "," >> output/combined.json
            fi
            echo "{\"file\": \"$(basename $file)\", \"content\": \"$content\"}" >> output/combined.json
          done
          echo "]" >> output/combined.json

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: combined-json
          path: output/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: combined-json
          path: output/

      - name: Get Current Timestamp
        id: timestamp
        run: echo "RELEASE_TAG=$(date +%s)" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: ${{ env.RELEASE_TAG }}
          body: "Release created automatically"
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/combined.json
          asset_name: combined.json
          asset_content_type: application/json
