name: Release on Main Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Combine .pem files into JSON
        run: |
          mkdir -p output
          echo "[" > output/combined.json
          for file in $(find . -name "*.pem"); do
            content=$(cat $file)
            echo "{\"file\": \"$(basename $file)\", \"content\": \"$content\"}," >> output/combined.json
          done
          sed -i '$ s/,$//' output/combined.json # Remove the last comma
          echo "]" >> output/combined.json

      - name: Create release version
        id: version
        run: echo "::set-output name=version::$(date -u +%Y%m%d%H%M%S)"

      - name: Upload release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: combined-json
          path: output/combined.json

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: combined-json

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.version }}
          release_name: Release ${{ needs.build.outputs.version }}
          body: |
            Automated release created on ${{ needs.build.outputs.version }}.
          draft: false
          prerelease: false

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: output/combined.json
          asset_name: combined.json
          asset_content_type: application/json
